// Code generated by go2go; DO NOT EDIT.


//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:1
package main

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:1
import (
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:1
 "fmt"
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:1
 "reflect"
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:1
 "sort"
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:1
)

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:22
func main() {
									s1 := []int{2, 3, 1}
									sorted1 := []int{1, 2, 3}
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:24
 instantiate୦୦Sort୦int(s1, func(a, b int) bool {
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:27
  return a < b
	})

	if !reflect.DeepEqual(s1, sorted1) {
		panic(fmt.Sprintf("want %v, got %v", sorted1, s1))
	}
									fmt.Printf("sorted: %v\n", s1)

									s2 := []float64{2.0, 3.0, 1.0}
									sorted2 := []float64{1, 2, 3}
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:36
 instantiate୦୦Sort୦float64(s2, func(a, b float64) bool {
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:39
  return a < b
	})

	if !reflect.DeepEqual(s2, sorted2) {
		panic(fmt.Sprintf("want %v, got %v", sorted2, s2))
	}
	fmt.Printf("sorted: %v\n", s2)

	type instantiate୦୦wrapSort୦float64 struct{}
}
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:18
func instantiate୦୦Sort୦int(s []int, cmp func(int, int,) bool) {
	sort.Sort(instantiate୦୦wrapSort୦int{s, cmp})
}
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:18
func instantiate୦୦Sort୦float64(s []float64, cmp func(float64, float64,) bool) {
	sort.Sort(instantiate୦୦wrapSort୦float64{s, cmp})
}

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:20
type instantiate୦୦wrapSort୦int struct {
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:10
 s   []int
									cmp func(int, int,) bool
}

func (s instantiate୦୦wrapSort୦int,) Len() int           { return len(s.s) }
func (s instantiate୦୦wrapSort୦int,) Less(i, j int) bool { return s.cmp(s.s[i], s.s[j]) }
func (s instantiate୦୦wrapSort୦int,) Swap(i, j int)      { s.s[i], s.s[j] = s.s[j], s.s[i] }

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:16
type instantiate୦୦wrapSort୦float64 struct {
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:10
 s   []float64
									cmp func(float64, float64,) bool
}

func (s instantiate୦୦wrapSort୦float64,) Len() int           { return len(s.s) }
func (s instantiate୦୦wrapSort୦float64,) Less(i, j int) bool { return s.cmp(s.s[i], s.s[j]) }
func (s instantiate୦୦wrapSort୦float64,) Swap(i, j int)      { s.s[i], s.s[j] = s.s[j], s.s[i] }

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:16
type Importable୦ int

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:16
var _ = fmt.Errorf
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:16
var _ = reflect.Append

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test1.go2:16
type _ sort.Float64Slice
