// Code generated by go2go; DO NOT EDIT.


//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:1
package main

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:1
import "fmt"

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:12
type aa struct {
	a int32
	b float64
}

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:18
type Stringer interface {
	String() string
}

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:29
type sa struct {
	name string
}
type b struct{}

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:33
func (a sa) String() string {
	return a.name
}

func main() {
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:37
 instantiate୦୦Print୦string([]string{"hello, ", "world\n"})
									instantiate୦୦Print୦int32([]int32{1, 2})
									instantiate୦୦Print୦float64([]float64{1.1, 2.2})

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:42
 aaList := make([]aa, 0, 2)
									aaList = append(aaList, aa{1, 1.1})
									aaList = append(aaList, aa{2, 2.2})
									aaList = append(aaList, aa{5, 5.5})
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:45
 instantiate୦୦Print୦main୮aaa(aaList)

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:48
 ret := instantiate୦୦Stringify୦main୮asa([]sa{{"fengzhu1"}, {"fengzhu2"}})
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:48
 instantiate୦୦Print୦string(ret)

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:51
}
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:5
func instantiate୦୦Print୦string(s []string,) {
	for _, v := range s {
		fmt.Print(v)
	}
	fmt.Println()
}
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:5
func instantiate୦୦Print୦int32(s []int32,) {
	for _, v := range s {
		fmt.Print(v)
	}
	fmt.Println()
}
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:5
func instantiate୦୦Print୦float64(s []float64,) {
	for _, v := range s {
		fmt.Print(v)
	}
	fmt.Println()
}
//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:5
func instantiate୦୦Print୦main୮aaa(s []aa,) {
	for _, v := range s {
		fmt.Print(v)
	}
	fmt.Println()
}

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:22
func instantiate୦୦Stringify୦main୮asa(s []sa) (ret []string) {
	for _, v := range s {
		ret = append(ret, v.String())
	}
	return ret
}

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:27
type Importable୦ int

//line /home/fengzhu/go/src/fengzhu/golang-study/go2go/test.go2:27
var _ = fmt.Errorf
